spring.datasource.url=jdbc:mysql://localhost:3306/sale_management
spring.datasource.username=root
spring.datasource.password=anhthanhpro2005

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=truespring.application.name=sale-management
